name: Deploy Playground to GitHub Pages
on:
  push:
    branches:
      - main
  workflow_dispatch:
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3 
      # this action has a built-in functionality for caching and restoring dependencies
      # https://github.com/actions/setup-node#caching-global-packages-data
        with:
          node-version: 16
      - name: Install and Build
        run: |
          npm ci
          npm run build
      - name: Deploy 🚀
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist/test-playground
